### Farid Abdalla & Noah Graells

# Exerice 2 : System evaluation

In [161]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd

syst_a = np.genfromtxt('ex2-system-a.csv', delimiter=';')
syst_b = np.genfromtxt('ex2-system-b.csv', delimiter=';')

In [162]:
# remove last empty col
syst_a = np.array([x[:-1] for x in syst_a])
syst_b = np.array([x[:-1] for x in syst_b])
print(syst_a.shape)
print(syst_b.shape)

# get the ground truth for each prediction
syst_a_gt = np.array([int(x[-1]) for x in syst_a])
syst_b_gt = np.array([int(x[-1]) for x in syst_b])
print(syst_a_gt)
print(syst_b_gt)

# remove the ground truth col from prediction arrays
syst_a = np.array([x[:-1] for x in syst_a])
syst_b = np.array([x[:-1] for x in syst_b])
print(syst_a.shape)
print(syst_b.shape)

(10000, 11)
(10000, 11)
[7 2 1 ... 4 5 6]
[7 2 1 ... 4 5 6]
(10000, 10)
(10000, 10)


### a) Classification decisions

In [163]:
def bayes_classification_decisions(preds):
    res = []
    for entry in preds:
        max_ind = 0
        for i in range(len(entry)):
            if entry[i] >= entry[max_ind]:
                max_ind = i
        res.append(max_ind)
     
    return res

In [164]:
syst_a_pred = np.array(bayes_classification_decisions(syst_a))
syst_b_pred = np.array(bayes_classification_decisions(syst_b))

### b) Error rate

In [165]:
def error_rate(gt, pred):
    return (gt != pred).sum()/len(gt)

In [166]:
print("System a error rate :", error_rate(syst_a_gt, syst_a_pred))
print("System b error rate :", error_rate(syst_b_gt, syst_b_pred))

System a error rate : 0.1073
System b error rate : 0.0387


### c) Confusion matrix

In [178]:
def confusion_matrix(gt, pred, class_count):
    conf_mat = np.array([[0 for x in range(class_count)] for x in range(class_count)])
    for i in range(len(gt)) :
        conf_mat[gt[i]][pred[i]] = conf_mat[gt[i]][pred[i]] + 1 
    return conf_mat

In [179]:
print("System a confusion matrix :")
a_conf_mat = confusion_matrix(syst_a_gt, syst_a_pred, 10)
print(a_conf_mat, "\n")

print("System b confusion matrix :")
b_conf_mat = confusion_matrix(syst_b_gt, syst_b_pred, 10)
print(b_conf_mat)

System a confusion matrix :
[[ 944    0   11    0    0    2   10    7    5    1]
 [   0 1112    2    3    1    4    3    1    9    0]
 [  10    6  921   12   15    3   19   15   26    5]
 [   1    1   31  862    2   72    5   14   12   10]
 [   2    3    6    2  910    1   12    6    4   36]
 [  12    3    6   29   19  768   19    9   21    6]
 [  14    3   21    2   22   28  865    0    3    0]
 [   0   14   30    9    7    2    1  929    3   33]
 [  12   16   18   26   24   46   22   19  772   19]
 [  10    4    6   22   53   18    0   48    4  844]] 

System b confusion matrix :
[[ 963    0    4    1    0    2    6    2    2    0]
 [   0 1123    3    1    0    0    5    1    2    0]
 [   5    0  996    7    4    0    4    8    6    2]
 [   0    0   13  985    0    3    1    3    3    2]
 [   1    2    4    0  938    1    9    2    5   20]
 [   8    1    0   27    1  830   12    1    8    4]
 [   6    3    2    1    7    4  930    1    4    0]
 [   0    7   18   10    3    1    0  98

### d) Precision and recall

In [ ]:
def 